
path: C:/Users/Nemo/Desktop/license_plate_recognition/vehicle_number_plate_detection # DATASET ROOT DIRECTORY
train: images/train
val: images/train


# classes

# names:
# 0: vehicle


nc: 1  # number of classes
names: ['license_plate']


